### ISSUE TITLE
get_average_price_per_month():

### ISSUE THREAD

**Issue by AhalaAyyalas** [sjasthi/python101_2023_gasprices_project#2]
Bug 1:  The names 1 to 12 are not user friendly from end user point of view
----- We want to display the Month names in "Jan", "Feb".. "Dec" format

Bug 2 : The average price needs to be rounded off to a.bc (2 digits after the decimal)

**Comment by MayukhaI12** [comment]
I'm not sure who was in charge of this code, but I fixed the two bugs. Hope this helps!

**Comment by MayukhaI12** [comment]
I'm not sure who was in charge of this code, but I fixed the two bugs. Hope this helps!
