### ISSUE TITLE
get_average_prices_per_month_dictionary():

### ISSUE THREAD

**Issue by AhalaAyyalas** [sjasthi/python101_2023_gasprices_project#3]
Months should be sorted from Jan to Dec: And only use three letter codes (not full names for the month). And the price should be displayed only till 2 digits after the decimal.

**Comment by MayukhaI12** [comment]
- The code displays only two digits after the decimal already.
- I have updated the code to use only three letter codes, like you said.
- However, the order of the months is out of our hands. We depend on the Cheetahs' code for this, and their code is ordered in the same way ours is.

Thank you for bringing this to our attention!

**Comment by AhalaAyyalas** [comment]
Hello Mayukha,

Thank you for the updates.
